[package]
name = "host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "host"
path = "src/main.rs"

[[bin]]
name = "checkin"
path = "src/bin/checkin.rs"

[[bin]]
name = "withdraw"
path = "src/bin/withdraw.rs"

[[bin]]
name = "resolve_game"
path = "src/bin/resolve_game.rs"

[[bin]]
name = "route_moult"
path = "src/bin/route_moult.rs"

[[bin]]
name = "spawn_children"
path = "src/bin/spawn_children.rs"

[[bin]]
name = "hatch"
path = "src/bin/hatch.rs"

[[bin]]
name = "fall"
path = "src/bin/fall.rs"

[[bin]]
name = "redeem"
path = "src/bin/redeem.rs"

[[bin]]
name = "fossilize"
path = "src/bin/fossilize.rs"

[[bin]]
name = "moult"
path = "src/bin/moult.rs"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "^3.0.5" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
hex = "0.4"
serde_json = "1.0"
sha2 = "0.10"
rand = "0.8"
